test browser: Disable headless Chrome for < v7.10
Turns out the `mocha-chrome` npm contains syntax that breaks on earlier
versions of Node. (Technically it becomes compatible sometime between
v7.4.0 and v7.10.0, but those are the only two versions from v7.x that
I've installed at the moment.)

  node_modules/mocha-chrome/bin/mocha-chrome:78
  (async function run () {
         ^^^^^^^^
  SyntaxError: Unexpected token function
      at Object.exports.runInThisContext (vm.js:78:16)
      at Module._compile (module.js:543:28)
      at Object.Module._extensions..js (module.js:580:10)
      at Module.load (module.js:488:32)
      at tryModuleLoad (module.js:447:12)
      at Function.Module._load (module.js:439:3)
      at Module.runMain (module.js:605:10)
      at run (bootstrap_node.js:420:7)
      at startup (bootstrap_node.js:139:9)
      at bootstrap_node.js:535:3