e2e: Wait for "Create" link in beforeEach
This should resolve the following failures:

- https://travis-ci.org/mbland/custom-links/jobs/260701744
- https://travis-ci.org/mbland/custom-links/jobs/260701972

This may also finally fix the flakiness observed in earlier builds, as
the problem was likely that the first `activeElement()` call came before
the expected element became active, considering that the view is set
by `loadApp()` some time after the DOMContentLoaded event. The hint was
the common failure message from both of the above builds:

```
 1) End-to-end test shows the no-links message before any links created:

      AssertionError: expected '| My links | New link | Log out\nCustom
Links' to deeply equal 'Create a new custom link'

      + expected - actual

      -| My links | New link | Log out
      -Custom Links
      +Create a new custom link
```